# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='attendees',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='detail',
            field=models.TextField(blank=True, default='N/A'),
        ),
    ]
