# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_calendar', '0002_auto_20160305_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='exchange_id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
